version: "3"
services:
  app:
    build: ./
    env_file: ./.env
    ports:
      - 80:80
    environment:
        APP_ENV: production
        PHP_EXTENSION_XDEBUG: 0
        PHP_EXTENSION_PGSQL: 1
        PHP_EXTENSION_PDO_PGSQL: 1
        PHP_EXTENSION_GD: 1
        APACHE_DOCUMENT_ROOT: /workspace/public
        PHP_INI_MEMORY_LIMIT: 4096M
        PHP_INI_POST_MAX_SIZE: 4096M
        PHP_INI_UPLOAD_MAX_FILESIZE: 2G
        PHP_MAX_EXECUTION_TIME: 3600
    networks:
      - lara
    links:
      - laradbpgsql
      - lararedis
  laradbpgsql:
    env_file: ./.env
    image: postgres:13
    restart: unless-stopped
    ports:
        - 5432:5432
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - lara 
  lararedis:
    env_file: ./.env
    image: redis:6-alpine
    ports:
      - 6379:6379
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - lara
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - lara

networks:
  lara:
    driver: bridge